apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  name: {{ include "webmethods-apigateway.fullname" . }}
data:
  {{- if .Values.fullConfigs }}
  full.yml: |
    {{- toYaml .Values.fullConfigs | nindent 4 }}
  {{- else }}
  {{- if .Values.commonConfigs }}
  common.yml: |
    {{- toYaml .Values.commonConfigs | nindent 4 }}
  {{- end }}
  {{- if include "webmethods-apigateway.isClusteringIgnite" .Values.clusteringType }}
  clustering_ignite.yml: |
    apigw:
      cluster:
        aware: true
        name: APIGatewayCluster
        sessTimeout: 60
        actionOnStartupError: shutdown
        ignite:
          discoveryPort: 47100
          communicationPort: 47500
          portRange: 5
          k8sServiceName: {{ include "webmethods-apigateway.gwruntimeFullname" . }}
          k8sNamespace: {{ .Release.Namespace }}
  {{- else }}
  {{- if include "webmethods-apigateway.isClusteringTerracotta" .Values.clusteringType }}
  clustering_terracotta.yml: |
    apigw:
      cluster:
        aware: true
        name: APIGatewayCluster
        sessTimeout: 60
        actionOnStartupError: shutdown
        tsaUrls: {{ .Value.clusteringTerracottaUrl }}
  {{- end }}
  {{- end }}
  {{- end }}