apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  name: {{ include "webmethods-apigateway.fullname" . }}
data:
  {{- if .Values.config }}
  common_settings.yml: |
    {{- toYaml .Values.config | nindent 4 }}
  {{- end }}