---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webmethods-apigateway.fullname" . }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webmethods-apigateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webmethods-apigateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webmethods-apigateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
        {{ toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerPorts }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            failureThreshold: 30
            exec:
              command:
              - /bin/bash
              - ./healthcheck.sh
              - "false"
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - ./healthcheck.sh
              - "true"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- with .Values.envConfigs }}
            {{- include "webmethods-apigateway.dictToEnvs" . | indent 12 }}
            {{- end }}
            {{- with .Values.envSecretConfigs }}
            {{- include "webmethods-apigateway.secretsDictToEnvs" . | indent 12 }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: configs-volume
              mountPath: /configs
            - name: wm-derbydb-volume
              mountPath: /opt/softwareag/IntegrationServer/instances/default/db
              subPath: wmderbydb
            {{- if .Values.apigwLicense }}
            {{- with .Values.apigwLicense.licenseSecret }}
            - name: apigateway-license
              mountPath: {{ .Values.apigwLicense.licenseMountPath }}
              subPath: {{ .path }}
              readOnly: false
            {{- end }}
            {{- end }}
            {{- if .Values.apigwTerracottaLicense }}
            {{- with .Values.apigwTerracottaLicense.licenseSecret }}
            - name: terracotta-license
              mountPath: {{ .Values.apigwTerracottaLicense.licenseMountPath }}
              subPath: {{ .path }}
              readOnly: false
            {{- end }}
            {{- end }}
      volumes:
      - name: configs-volume
        configMap:
          name: {{ include "webmethods-apigateway.fullname" . }}
      - name: wm-derbydb-volume
        emptyDir:
          sizeLimit: 5Gi
      {{- if .Values.apigwLicense }}
      {{- with .Values.apigwLicense.licenseSecret }}
      - name: apigateway-license
        secret:
          secretName: {{ .name }}
          items:
          - key: {{ .key }}
            path: {{ .path }}
      {{- end }}
      {{- end }}
      {{- if .Values.apigwTerracottaLicense }}
      {{- with .Values.apigwTerracottaLicense.licenseSecret }}
      - name: terracotta-license
        secret:
          secretName: {{ .name }}
          items:
          - key: {{ .key }}
            path: {{ .path }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}