---
{{- if .Values.ingress.gwruntime.enabled -}}
{{- $uname := (include "webmethods-apigateway.gwruntimeFullname" .) }}
{{- $port := .Values.service.gwruntime.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $uname }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.gwruntime.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.gwruntime.tls }}
  tls:
    {{- range .Values.ingress.gwruntime.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.gwruntime.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.gwruntime.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ $uname }}
                port:
                  number: {{ $port }}
          {{- end }}
{{- end }}
---
{{- if .Values.ingress.gwui.enabled -}}
{{- $uname := (include "webmethods-apigateway.gwuiFullname" .) }}
{{- $port := .Values.service.gwui.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $uname }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.gwui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.gwui.tls }}
  tls:
    {{- range .Values.ingress.gwui.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.gwui.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.gwui.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ $uname }}
                port:
                  number: {{ $port }}
          {{- end }}
{{- end }}
---
{{- if .Values.ingress.custom.enabled -}}
{{- $uname := (include "webmethods-apigateway.fullname" .) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $uname }}
  labels:
    {{- include "webmethods-devportal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ .backendServiceName }}
                port:
                  number: {{ .backendServicePort }}
          {{- end }}
    {{- end }}
{{- end -}}