# Default values for webmethods-apigateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: ghcr.io/softwareag-government-solutions
  repository: webmethods-apigateway
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: dev-10.11-latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# dict of envs
envConfigs: {}
envSecretConfigs: {}

# we have to setup 2 different service, because 1 is sticky, not the other...
service:
  gwruntime:
    type: ClusterIP
    port: 5555
    annotations: {}
  gwui:
    type: ClusterIP
    port: 9072
    annotations: {}

containerPorts:
  - containerPort: 5555
    name: gwruntime
    protocol: TCP
  - containerPort: 5543
    name: gwruntimessl
    protocol: TCP
  - containerPort: 9072
    name: gwui
    protocol: TCP
  - containerPort: 9073
    name: gwuissl
    protocol: TCP

# external configs
config:
  apigw:
    elasticsearch:
      autostart: false
      http:
        keepAlive: true
        keepAliveMaxConnections: 10
        keepAliveMaxConnectionsPerRoute: 100
        connectionTimeout: 1000
        socketTimeout: 10000
        maxRetryTimeout: 100000
      https:
        enabled: false
      sniff:
        enable: false
        timeInterval: 1000
      outboundProxy:
        enabled: false
        alias: somealias
      clientHttpResponseSize: 1001231
    kibana:
      autostart: false

# the licensing needed for the product
apigwLicenseSecret: {}
  # name: ""
  # key: ""
  # path: ""

apigwTerracottaLicenseSecret: {}
  # name: ""
  # key: ""
  # path: ""

configurator:
  enabled: false
  verbose: false
  envConfigs: {}
  envSecretConfigs: {}

ingress:
  gwruntime:
    enabled: false
    annotations: {}
    host: chart-example.local
    # tls:
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
    paths:
      - path: /gateway
        pathType: Prefix
      - path: /rest
        pathType: Prefix
      - path: /invoke
        pathType: Prefix
      - path: /WmAPIGateway
        pathType: Prefix
  gwui:
    enabled: false
    annotations: {}
    host: chart-example.local
    # tls:
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
    paths:
      - path: /
        pathType: Prefix
  custom:
    enabled: false
    annotations: {}
    hosts:
      - host: chart-example.local
        paths: []
          # - path: /
          #   pathType: Prefix
          #   backendServiceName: someservice
          #   backendServicePort: 5555
    # tls:
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}