apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-terracotta.fullname" . }}-hl
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    {{- include "webmethods-terracotta.labels" . | nindent 4 }}
spec:
  # Headless Service: This is needed for statefulset hostnames like terracotta-0 to resolve
  clusterIP: None
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  ports:
    - name: tsaport
      port: 9510
    - name: jmxport
      port: 9520
    - name: groupport
      port: 9530
    - name: mgtport
      port: 9540
  selector:
    {{- include "webmethods-terracotta.selectorLabels" . | nindent 4 }}
