# Default values for webmethods-devportal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/softwareag-government-solutions/webmethods-devportal
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: dev-10.11-latest
  imagePullSecrets: []

service:
  type: ClusterIP
  port: 18101
  annotations: {}

containerPorts:
  - containerPort: 18101
    name: httpui
    protocol: TCP
  - containerPort: 18102
    name: httpsui
    protocol: TCP

settings:
  tenant: tenant1
  loadbalancerUrl: ""
  javaMemMin: 1g
  javaMemMax: 1g
  javaOpts: ""
  envConfigs: {}
  envSecretConfigs: {}
  licenseSecret:
    name: ""
    key: ""
    path: ""
  licensePath: "/opt/softwareag/licenseKey.xml"  
  clustering:
    enabled: true
  elastic:
    uris: "http://es:9200"
    username: elastic
    passwordSecret:
      name: ""
      key: ""
  waitforelastic:
    enabled: true
    image:
      repository: "ubi8-minimal"
      pullPolicy: IfNotPresent
      tag: "latest"

configurator:
  enabled: false
  verbose: false
  sampleData: false
  image:
    repository: ""
    pullPolicy: IfNotPresent
    tag: ""
    imagePullSecrets: []
  envConfigs: {}
  envSecretConfigs: {}
  envSampleDataConfigs: {}
  envSampleDataSecretConfigs: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
        # - path: /
        #   pathType: Prefix
        #   backendServiceName: someservice
        #   backendServicePort: 5555
  # tls:
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
